USE PROJECT_ECOMMERCE;

SELECT * FROM PRODUCTS;


INSERT INTO PRODUCTS 
(PRODUCT_NAME, PRODUCT_TYPE, PRICE, QUANTITY)
VALUES
('Design Patterns: Elements of Reusable Object-Oriented Software', 'Book', 15.58 , 500);

INSERT INTO PRODUCTS 
(PRODUCT_NAME, PRODUCT_TYPE, PRICE, QUANTITY)
VALUES
('The Skyrim Library - Volumes I, II & III (Box Set)', 'Book', 54.28 , 100);

INSERT INTO PRODUCTS 
(PRODUCT_NAME, PRODUCT_TYPE, PRICE, QUANTITY)
VALUES
('The Lord of the Rings', 'Book', 41.98 , 1000);

INSERT INTO PRODUCTS 
(PRODUCT_NAME, PRODUCT_TYPE, PRICE, QUANTITY)
VALUES
('KingSpec SSD hdd 2.5 SATA3 SSD', 'Storage Devices', 125.78 , 5000);

INSERT INTO PRODUCTS 
(PRODUCT_NAME, PRODUCT_TYPE, PRICE, QUANTITY)
VALUES
('Kitchen Scale Digital Jewelry 200/500g 0.01g High Accuracy Backlight LCD Display', 'Kitchen', 14.72 , 250);
